services:
  relational-migrator:
    image: public.ecr.aws/v4d7k6c9/relational-migrator:latest
    ports:
      - "8080:8080"
    restart: always

  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "9090:8080"
 
volumes:
  pgdata: